### ISSUE TITLE
PID probe should work with remote hosts

### ISSUE THREAD

**Issue by MadJlzz** [MadJlzz/madprobe#2]
**Is your feature request related to a problem? Please describe.**
As we can see [here](https://github.com/MadJlzz/madprobe/blob/25a3e8f1ba2e7ce74efe252bda889f83606c0d56/internal/probe/pid.go#L18), PID probe only works locally.

**Describe the solution you'd like**
It could be nice by setting a PID probe like:
```
pid:
  - name: simple-remote-pid-probe
    hostname: remote.dev
    service-account: madjlzz
    pid: 1
    delay: 30
```
to connect to the concerned hostname and launch the check from here.
A solution could be to connect with SSH to the given server with the given username if SSH keys are configured on both client and server. 
The response should then be visible from the UI.

**Describe alternatives you've considered**
No alternatives have been considered.

**Additional context**
No additional context.
